// src/constants/commodities.js

const COMMODITIES = {
  TOMATO_LOCAL: "TOMATO_LOCAL",
  TOMATO_HYBRID: "TOMATO_HYBRID",
  PEPPER: "PEPPER",
  OKRA: "OKRA",
  GARDEN_EGGS: "GARDEN_EGGS",
  CABBAGE: "CABBAGE",
  LETTUCE: "LETTUCE",
  CUCUMBER: "CUCUMBER",
  ONION: "ONION",
};

module.exports = COMMODITIES;
